name: if-demo
on: 
  push:
    branches:
      - main
      - develop
jobs:
  if-demo:
    runs-on: ubuntu-latest
    steps:
      - name: run this step
        if: github.actor== 'rekha580'
        run: echo "this is main branch"
         
